goLexerExecFileName:=exec-lexer-go
javaLexerExecFileName:=exec-lexer-java


build-go-lexer:
	go build go/$(goLexerExecFileName) go/main.go

build-java-lexer:
	javac java/$(javaLexerExecFileName) java/Main.java

run-go-lexer:
	./go/$(goLexerExecFileName)

run-java-lexer:
	./java/$(javaLexerExecFileName)